export const CLIENTE_REGISTER_REQUEST = "CLIENTE_REGISTER_REQUEST";
export const CLIENTE_REGISTER_SUCCESS = "CLIENTE_REGISTER_SUCCESS";
export const CLIENTE_REGISTER_FAIL = "CLIENTE_REGISTER_FAIL";
export const CLIENTE_REGISTER_RESET = "CLIENTE_REGISTER_RESET";

export const CLIENTE_SIGNOUT = "CLIENTE_SIGNOUT";

export const CLIENTE_DETAILS_REQUEST = "CLIENTE_DETAILS_REQUEST";
export const CLIENTE_DETAILS_SUCCESS = "CLIENTE_DETAILS_SUCCESS";
export const CLIENTE_DETAILS_FAIL = "CLIENTE_DETAILS_FAIL";
export const CLIENTE_DETAILS_RESET = "CLIENTE_DETAILS_RESET";

export const CLIENTE_LIST_REQUEST = "CLIENTE_LIST_REQUEST";
export const CLIENTE_LIST_SUCCESS = "CLIENTE_LIST_SUCCESS";
export const CLIENTE_LIST_FAIL = "CLIENTE_LIST_FAIL";
export const CLIENTE_LIST_RESET = "CLIENTE_LIST_RESET";

export const CLIENTE_UPDATE_PROFILE_REQUEST = "CLIENTE_UPDATE_PROFILE_REQUEST";
export const CLIENTE_UPDATE_PROFILE_SUCCESS = "CLIENTE_UPDATE_PROFILE_SUCCESS";
export const CLIENTE_UPDATE_PROFILE_FAIL = "CLIENTE_UPDATE_PROFILE_FAIL";
export const CLIENTE_UPDATE_PROFILE_RESET = "CLIENTE_UPDATE_PROFILE_RESET";

export const CLIENTE_UPDATE_REQUEST = "CLIENTE_UPDATE_REQUEST";
export const CLIENTE_UPDATE_SUCCESS = "CLIENTE_UPDATE_SUCCESS";
export const CLIENTE_UPDATE_FAIL = "CLIENTE_UPDATE_FAIL";
export const CLIENTE_UPDATE_RESET = "CLIENTE_UPDATE_RESET";

export const CLIENTE_DELETE_REQUEST = "CLIENTE_DELETE_REQUEST";
export const CLIENTE_DELETE_SUCCESS = "CLIENTE_DELETE_SUCCESS";
export const CLIENTE_DELETE_FAIL = "CLIENTE_DELETE_FAIL";
export const CLIENTE_DELETE_RESET = "CLIENTE_DELETE_RESET";

export const CLIENTE_GETBYRIF_REQUEST = "CLIENTE_GETBYRIF_REQUEST";
export const CLIENTE_GETBYRIF_SUCCESS = "CLIENTE_GETBYRIF_SUCCESS";
export const CLIENTE_GETBYRIF_FAIL = "CLIENTE_GETBYRIF_FAIL";
export const CLIENTE_GETBYRIF_RESET = "CLIENTE_GETBYRIF_RESET";
