
export const listaMarcas = [
  "",
  "Sin Marca",
  "Otro",
  "Puma",
  "Salomon",
  "Nike",
  "Adidas",
  "Vans",
  "Generico",
  "Louis Vuitton",
  "D&G",
  "Valentino",
  "Prada",
  "Fendi",
  "Phillip Plain",
  "Burberry",
  "Converse",
  "Alexander mcQueen",
  "Balenciaga",
  "Birkenstock",
  "Dior",
  "New Balance",
  "Asics",
  "Polo",
  "Lacoste",
  "Boss",
  "Enporio",
  "Gant",
  "Tommy Hilfiger",
  "Fila",
  "Columbia",
  "Gorila",
  "Under Armon",
  "Calvin Klein",
  "DQ2",
  "Jordan",
  "Gucci",
  "Lagerfeld",
  "Monclear",
  "Palm",
  "Versace",
  "X OFF",
  "Zoom",
];

export const listaCategorias = ["", "CALZADO", "TEXTILES", "ACCESORIOS", "UTENSILIOS", "JUGUETES", "OTROS"];

export const listaColores = [
  "",
  "Blanco",
  "Negro",
  "Gris",
  "Azul",
  "Verde",
  "Amarillo",
  "Rojo",
  "Rosado",
  "Morado",
  "Vinotinto",
  "Celeste",
  "Naranja",
  "Fucsia",
  "Marron",
  "Beige",
  "Dorado",
  "Plateado",
  "Varios",
  "Otro",
];

export const listaModelos = [
  "",
  "Archlight",
  "Arizona Eva",
  "Awaiking",
  "Drawstring",
  "Greca",
  "Ikonik",
  "One",
  "Oversized",
  "Portofino",
  "Ramsey",
  "Rivoli",
  "Rocksrunner",
  "Roma",
  "Runnning",
  "San Bartolo",
  "Trainer",
  "VL7N",
  "White Tigreca",
  "Zero",
  "Airforce 1",
  "Jordan 1",
  "Retro 1",
  "Retro 2",
  "Retro 3",
  "Retro 4",
  "Retro 5",
  "Retro 6",
  "Retro 11",
  "AirMax",
  "Bad Bunny",
  "Benito",
  "Superstar",
  "Nike-SB",
  "Otro",
  "Stay Loyal 2",
  "Retro 12",
  "Jordan 13",
  "Sin Modelo",
  "Generico",
];

export const listaTipos = [
  "",
  "Alta Gama",
  "Casual",
  "Deportivo",
  "Sandalias",
  "Camisa",
  "Franela",
  "Short",
  "Mono",
  "Chemise",
  "Sweater",
  "Otro",
];

export const tallasObj = [
  { 20: 0 },
  { 21: 0 },
  { 22: 0 },
  { 23: 0 },
  { 24: 0 },
  { 25: 0 },
  { 26: 0 },
  { 27: 0 },
  { 28: 0 },
  { 29: 0 },
  { 30: 0 },
  { 31: 0 },
  { 32: 0 },
  { 33: 0 },
  { 34: 0 },
  { 35: 0 },
  { 36: 0 },
  { 37: 0 },
  { 38: 0 },
  { 39: 0 },
  { 40: 0 },
  { 41: 0 },
  { 42: 0 },
  { 43: 0 },
  { 44: 0 },
  { 45: 0 },
  { 46: 0 },
  { 47: 0 },
  { XS: 0 },
  { SS: 0 },
  { S: 0 },
  { M: 0 },
  { L: 0 },
  { XL: 0 },
  { XXL: 0 },
  { XXXL: 0 },
  { U: 0 },
  { G: 0 },
];

export const listaGeneros = ["", "Dama", "Caballero", "Niño", "Unisex", "N/A"];

export const categorias = [
  "",
  "Nomina",
  "Suministros",
  "Repuestos",
  "Aceite",
  "Servicio",
  "soporte",
  "Mecanico",
  "Alquileres",
  "Reparaciones",
  "Mano de Obra",
  "Prestamos",
  "Taxis",
  "Comidas y Refrigerios",
  "Pago Publicidad",
  "Pago Internet",
  "Pago Telefonia",
  "Pago Gasolina",
  "Otros Gastos",
  "Intercambio Publicitario",
  "Pago a Influencers",
  "Edicion de Videos",
  "Redes Sociales",
  "Ferreteria",
];

export const nombres = [
  " ",
  "Rony Paul",
  "Ronald Paul",
  "Franklin Bolivar",
  "Omar Bachir",
  "Reinaldo Perdomo",
  "Margaris Blanco",
  "Nayluz Lopez",
  "Enderson Montilla",
  "Alejandro Bolivar",
  "Yefraini",
  "Manuel Martinez",
];

export const listaFormaPago = [
  "",
  "EFECTIVO DOLARES",
  "EFECTIVO EUROS",
  "EFECTIVO BOLIVARES",
  "PAGOMOBIL",
  "TRANSFERENCIA",
  "ZELLE",
  "PUNTO DE VENTA",
];

export const listaBancos = [
  "",
  "PLAZA",
  "BANESCO",
  "VENEZUELA",
  "BICENTENARIO",
  "MERCANTIL",
  "BANCAMIGA",
  "BANPLUS",
  "PROVINCIAL",
  "CARIBE",
  "BNC",
  "VZLNO CREDITO",
  "TESORO",
];

export const listaCondiciones = [
  "",
  "CONTADO",
  "CREDITO",
  "INTERCAMBIO",
  "DONACION",
  "DOTACION",
  "CONSIGNACION",
  "PRESTAMO",
];

export const listaCanales = [
  "",
  "INSTAGRAM",
  "TIK-TOK",
  "FACEBOOK",
  "REFERIDO",
  "CUENTA-PROPIA",
  "RECOMENDADO",
  "EMISORA-RADIO",
  "TELEVISION",
  "PUBLICIDAD",
  "FLYERS",
];

export const listaSucursales = ["TIENDA-CHACAO1", "TIENDA-MERPOESTE", "CONSIGNACION1", "CONSIGNACION2"];

export const tipoRepo = ["", "REPOSICION", "INVENTARIO-INICIAL"];


export const listaTallas = [
  { value: "T20", label: "20" },
  { value: "T21", label: "21" },
  { value: "T22", label: "22" },
  { value: "T23", label: "23" },
  { value: "T24", label: "24" },
  { value: "T25", label: "25" },
  { value: "T26", label: "26" },
  { value: "T27", label: "27" },
  { value: "T28", label: "28" },
  { value: "T29", label: "29" },
  { value: "T30", label: "30" },
  { value: "T31", label: "31" },
  { value: "T32", label: "32" },
  { value: "T33", label: "33" },
  { value: "T34", label: "34" },
  { value: "T35", label: "35" },
  { value: "T36", label: "36" },
  { value: "T37", label: "37" },
  { value: "T38", label: "38" },
  { value: "T39", label: "39" },
  { value: "T40", label: "40" },
  { value: "T41", label: "41" },
  { value: "T42", label: "42" },
  { value: "T43", label: "43" },
  { value: "T44", label: "44" },
  { value: "T45", label: "45" },
  { value: "T46", label: "46" },
  { value: "T47", label: "47" },
  { value: "TXS", label: "XS" },
  { value: "TSS", label: "SS" },
  { value: "TS", label: "S" },
  { value: "TM", label: "M" },
  { value: "TL", label: "L" },
  { value: "TXL", label: "XL" },
  { value: "T2XL", label: "2XL" },
  { value: "T3XL", label: "3XL" },
  { value: "T4XL", label: "4XL" },
  { value: "T5XL", label: "5XL" },
  { value: "T6XL", label: "6XL" },
  { value: "TU", label: "U" },
  { value: "TG", label: "G" },
];


export const selectCanal = [
  "",
  "INSTAGRAM",
  "TIK-TOK",
  "FACEBOOK",
  "REFERIDO",
  "CUENTA-PROPIA",
  "RECOMENDADO",
  "EMISORA-RADIO",
  "TELEVISION",
  "PUBLICIDAD",
  "FLYERS",
];